### ISSUE TITLE
[BUG]: Icon alignment in trees

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1481] opened 2024-03-23 13:58 UTC
**Describe the bug**
At some point the icon and text is not vertically aligned:

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/0e56e130-8a49-466b-9c15-09f2ba47ada0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 122

**Comment by iOvergaard** [comment] 2024-03-24 20:23
Thanks for reporting. This seems to be a duplicate of #1457 and should be fixed with #1477.

**Closed by iOvergaard** 2024-03-24 20:23 UTC
Labels: type/bug
